# Netlify configuration for OpenEHR Healthcare System

[build]
  # No build command needed - static site
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Redirect rules for clean URLs
[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/viewer"
  to = "/viewer.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom 404 page (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
